INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('ammonium_nitrate', 'Ammonium nitrate', 1, 0, 1),
	('ampul1', 'Ampulemine No 1', 1, 0, 1),
	('ampul2', 'Ampulemine No 2', 1, 0, 1),
	('ampul3', 'Ampulemine No 3', 1, 0, 1),
	('codeine', 'Codeine', 1, 0, 1),
	('citrus_drink', 'Sprunt', 1, 0, 1),
	('drug_ecstasy', 'Ecstasy', 1, 0, 1),
	('drug_lean', 'Lean', 1, 0, 1),
	('drug_lsd', 'LSD', 1, 0, 1),
	('drug_meth', 'Meth', 1, 0, 1),
	('hydrogen', 'Hydrogen', 1, 0, 1),
	('ice', 'Ice', 1, 0, 1),
	('candy', 'Candy', 1, 0, 1),
	('sulfuric_acid', 'Sulfur Acid', 1, 0, 1),
	('muriatic_acid', 'Muriatic Acid', 1, 0, 1),
	('nitrogen', 'Nitrogen', 1, 0, 1),
	('oxygen', 'Oxygen', 1, 0, 1),
	('pseudoephedrine', 'Pseudoephedrine', 1, 0, 1),
	('red_phosphorus', 'Red Phosphorus', 1, 0, 1),
	('sodium_hydroxide', 'Sodium hydroxide', 1, 0, 1),